name: jono_hospital
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  google_maps_flutter: ^2.2.2
  geolocator: ^9.0.2


  cupertino_icons: ^1.0.2
  custom_info_window: ^1.0.1
  flutter_svg: ^2.0.1
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.8
  cloud_firestore: ^4.4.2
  multiple_result: ^4.0.0
  http: ^0.13.5
  uuid: ^3.0.7
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/map_style/
    - assets/svgs/
    - assets/images/
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
